wildfly/galleon

maven-plugins/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java

This patch enables the configuration of the provisioning runtime log according to the maven debug option.
Jira issue: https://issues.jboss.org/browse/GAL-22

[GAL-22] Provisioning runtime verbose log is ignored with maven execution in debug mode

---

maven-plugins/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java
maven-plugins/src/main/java/org/jboss/galleon/maven/plugin/util/MavenArtifactRepositoryManager.java

Currently, we are requesting artifact resolutions without setting in the request any remote repository.
That means, if we are using the Maven resolver, the artifact won't be downloaded.
Jira issue: https://issues.jboss.org/browse/GAL-35

[GAL-35] Add remote repository list to the Artifact resolution requests

---

cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateEditCommand.java
cli/src/main/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioning.java
cli/src/test/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioningTestCase.java
core/src/main/java/org/jboss/galleon/config/ConfigCustomizationsBuilder.java
core/src/main/java/org/jboss/galleon/config/FeaturePackConfig.java

When including config or package, the item is automatically removed from exluded items. Similarly when
excluding items.
https://issues.jboss.org/projects/GAL/issues/GAL-21

GAL-21 config and package inclusion/exclusion improvements

---

maven-plugins/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java
maven-plugins/src/main/java/org/jboss/galleon/maven/plugin/util/MavenArtifactRepositoryManager.java

Add a plugin option to enable work in an offline mode where the plugin will resolve artifacts only using the Maven local repository.
Jira issue: https://issues.jboss.org/browse/GAL-34

[GAL-34] Add offline mode to provisioning plugin

---

cli/src/main/java/org/jboss/galleon/cli/model/FeatureSpecsBuilder.java
core/src/main/java/org/jboss/galleon/layout/FeaturePackLayoutDescriber.java
core/src/main/java/org/jboss/galleon/layout/ProvisioningLayoutFactory.java
core/src/main/java/org/jboss/galleon/util/HashUtils.java
core/src/main/java/org/jboss/galleon/util/ZipUtils.java
maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducer.java
maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenUniverse.java

1) Moved all usages of newFileSystem to ZipUtils. It allows for better control on newFileSystem calls.
2) Replaced calls to newFileSystem(URI) that can take a file path to newFileSystem(Path), this call is thread safe.
3) The remaining call (a single one) that takes an URI has not to be synchronized, could be made if needed (prototype of it not present in this PR).
3) Made producers and channels zip file extraction thread safe.
4) ProvisioningLayoutFactory.resolveFeaturePackDir synchronized to avoid concurrent unzip.
galleon-plugins (WfInstall plugin) should be updated to call into ZipUtils when creating new file system. Not strictly needed but would increase consistency.

Fix for GAL-51, make early initialization and installation to run concurrently safely

---

core/src/main/java/org/jboss/galleon/ArtifactCoords.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/FeaturePack.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/ResolveLocalArtifactItem.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/ResolveLocalItem.java

This patch allows specifying a feature pack path in the provisioning plugin, additionally, the feature pack dependencies can be specified using a GAV or a path to a file. These configurations will allow resolving feature packs without using Universe.
Jira issue: https://issues.jboss.org/browse/GAL-67

[GAL-67] Allow maven provisioning plugin to locate feature packs using a file path

---

cli/src/main/java/org/jboss/galleon/cli/AbstractStateCommand.java
cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/ProvisioningCommand.java
cli/src/main/java/org/jboss/galleon/cli/UninstallCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractCommaSeparatedCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/CommandWithInstallationDirectory.java
cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledFPLCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledProducerCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractProvisionWithPlugins.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/DiffCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/StateProvisionCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateCheckUpdatesCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateUpgradeCommand.java
docs/guide/tool/state.adoc
testsuite/src/test/java/org/jboss/galleon/cli/InstallUpdateTestCase.java

- upgrade command to accept plugin options
- --products=<comma separated list of installed producerSpec> added to check-updates and upgrade commands.
- diff command is hidden. Keeping impl for reference and possible future usage. 
- test of identified producer upgrade.
- tool documentation to introduce FPL|FPID and general concepts. Added doc for upgrade.

Fix for GAL-75 and doc

---

cli/src/main/java/org/jboss/galleon/cli/AbstractStateCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java
cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/InfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateCheckUpdatesCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/configuration/AbstractDefaultConfigCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/feature/StateAddFeatureCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractPackageCommand.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfig.java
cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainer.java
cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java
cli/src/main/java/org/jboss/galleon/cli/model/FeaturePackInfo.java
cli/src/main/java/org/jboss/galleon/cli/model/ProvisioningInfo.java
cli/src/main/java/org/jboss/galleon/cli/path/FeatureContainerPathConsumer.java
docs/guide/tool/state.adoc
testsuite/src/test/java/org/jboss/galleon/cli/PatchTestCase.java
testsuite/src/test/java/org/jboss/galleon/cli/PatchTransitiveDepTestCase.java

- No more 'patches' type of info, patches displayed when appropriate.
- Seperate installed vs dependencies. 
- Introduced all type to display all, by default only display installed (fast).
- New unit test for transitive dependency patching info.

Fix for GAL-81, minimize patch related information. Reworked state info

---

cli/src/main/java/org/jboss/galleon/cli/AbstractStateCommand.java
cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractCommaSeparatedCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java
cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledFPLCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledProducerCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateExploreCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java
cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainer.java
cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java

- GAL-96, update completer display transitive deps, ProvisioningLayout to retrieve dependencies.
- Renamed Channel to be Update Channel
- Display nothing for empty install

Fix for GAL-96, better support for transitive dependencies.

---

cli/src/main/java/org/jboss/galleon/cli/CliMain.java
cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/UniverseManager.java
cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractDynamicCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractPluginsCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractProvisionWithPlugins.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/DiffCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/InstallCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/StateProvisionCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateUpdateCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/feature/StateAddFeatureCommand.java
cli/src/main/java/org/jboss/galleon/cli/resolver/PluginResolver.java
cli/src/main/java/org/jboss/galleon/cli/resolver/ResourceResolver.java
docs/guide/tool/state.adoc

- Removed experimental sys property
- Background resolution does only resolve producers and channels, no plugins.
- Plugin options are completed when appropriate. Still some latency but that is the current "state of the art", latency is acceptable.
- Options can be displayed when getting info for an installation.
- Documented the possible latency (possible because options could have been retrieved by previous provisioning commands).

Fix for GAL-103, re-activate plugin options completion

---

cli/src/main/java/org/jboss/galleon/cli/Util.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenCliSettings.java
docs/guide/tool/maven.adoc

Doing so the latest builds are discovered, this policy is being documented as the proper one.

Fix for GAL-117, change mvn update NEVER_UPDATE policy to DAILY_UPDATE

---

cli/src/main/java/org/jboss/galleon/cli/Util.java
cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenAddRepository.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenInfo.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenSetReleasePolicy.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenSetSnapshotPolicy.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenCliSettings.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfig.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfigXml.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenRemoteRepository.java
docs/guide/tool/maven.adoc
testsuite/src/test/java/org/jboss/galleon/cli/CliWrapper.java
testsuite/src/test/java/org/jboss/galleon/cli/MavenConfigTestCase.java

- Never for snapshots, Daily for releases.
- Can update/reset and persist default policies. Completer to help set right policy.
- New policy update options when adding remote repository
- mvn commands testing.

Fix for GAL-121, snapshot never, release daily. Make policies configurable

---

cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/cmd/BooleanCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenAddRepository.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenEnableRelease.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenEnableSnapshot.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenInfo.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenCliSettings.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfig.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfigXml.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenRemoteRepository.java
docs/guide/tool/maven.adoc
testsuite/src/test/java/org/jboss/galleon/cli/MavenConfigTestCase.java

- Snapshot not resolved from remote repo by default.
- Configuration items to enable/disable activation globally and per repo.
- New tests.

Fix for GAL-122, CLI maven release vs snapshot activation

---

cli/src/main/java/org/jboss/galleon/cli/CliMain.java
cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractDynamicCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java
cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/ClearCacheCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractPluginsCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractProvisionWithPlugins.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/StateProvisionCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/UninstallCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateUpdateCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/feature/StateAddFeatureCommand.java
cli/src/main/java/org/jboss/galleon/cli/config/Configuration.java
core/src/main/java/org/jboss/galleon/cache/FeaturePackCacheManager.java
core/src/main/java/org/jboss/galleon/layout/ProvisioningLayoutFactory.java
core/src/main/java/org/jboss/galleon/universe/Channel.java
core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1Channel.java
docs/guide/tool/state.adoc
maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenChannel.java
testsuite/src/test/java/org/jboss/galleon/cache/FeaturePackCacheManagerTestCase.java
testsuite/src/test/java/org/jboss/galleon/cli/CliTestCase.java
testsuite/src/test/java/org/jboss/galleon/cli/CliWrapper.java

- Cache of feature-pack
- CLI to manage cache.
- Removed part of plugin options caching done in CLI.
- Automatic removal of old content from cache.
- Prepare for non interactive mode.
- New cache related tests.

Fix for GAL-118, layout cache controlled by CLI

---

cli/src/main/java/org/jboss/galleon/cli/Arguments.java
cli/src/main/java/org/jboss/galleon/cli/CliMain.java
cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/PmSessionCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java
cli/src/main/java/org/jboss/galleon/cli/config/Configuration.java
cli/src/main/java/org/jboss/galleon/cli/terminal/CliShell.java
cli/src/main/java/org/jboss/galleon/cli/terminal/CliShellInvocationProvider.java
cli/src/main/java/org/jboss/galleon/cli/terminal/CliShellPmCommandInvocation.java
cli/src/main/java/org/jboss/galleon/cli/terminal/CliTerminalConnection.java
cli/src/main/java/org/jboss/galleon/cli/terminal/InteractiveInvocationProvider.java
cli/src/main/java/org/jboss/galleon/cli/terminal/InteractivePmCommandInvocation.java
cli/src/main/java/org/jboss/galleon/cli/terminal/OutputInvocationProvider.java
cli/src/main/java/org/jboss/galleon/cli/terminal/OutputPmCommandInvocation.java
cli/src/test/java/org/jboss/galleon/cli/ArgumentsTestCase.java
content/bin/galleon.sh
do.sh
docs/guide/tool/state.adoc
pom.xml

- Command as argument
- File of commands
- Reworked aesh integration to offer the proper Invocation context according to the execution context: interactive console, non interactive console, tests. This has the benefit to offer advanced terminal  capabilities (ANSI and read input) on all platforms  when run with non interactive console.
- Evolved aesh dependency to latest released one 1.7. Still planned to upgrade to 1.8 to solve known issues.

Fix for GAL-123, non interactive console support

---

cli/src/main/java/org/jboss/galleon/cli/CliMain.java
cli/src/main/java/org/jboss/galleon/cli/UniverseManager.java
cli/src/main/java/org/jboss/galleon/cli/Util.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/AbstractInstallationCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/AddUniverseCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/ClearHistoryCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/ExportCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/RemoveUniverseCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/AbstractProvisioningCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/CheckUpdatesCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/ProvisionCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/UndoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/UpdateCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractProvisionWithPlugins.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateEditCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateExportCommand.java

- Use builtin aesh support when possible (static commands).
- Rely on aesh file converter for dynamic commands.
- Added some File/dir existence checks.
- Removed some redundancy.

Fix for GAL-128, CLI, support ~ in paths

---

cli/src/main/java/org/jboss/galleon/cli/PmCommandInvocation.java
cli/src/main/java/org/jboss/galleon/cli/Util.java
core/src/main/java/org/jboss/galleon/creator/tasks/StringToFile.java
core/src/main/java/org/jboss/galleon/diff/FileSystemDiff.java

https://issues.jboss.org/browse/GAL-136 - Arguments in wrong order
Methods signatures:
```
public static String formatColumns(List<String> lst, int width, int height) {
```
```
protected StringToFile(String content, String relativeTarget, boolean isContent) { 
```
```
public static <T> Patch<T> diff(List<T> original, List<T> revised) {
```

[GAL-136] Arguments in wrong order

---

cli/src/main/java/org/jboss/galleon/cli/HelpSupport.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/ExportCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateExportCommand.java
cli/src/main/java/org/jboss/galleon/cli/terminal/CliTerminalConnection.java
cli/src/test/java/org/jboss/galleon/cli/HelpSupportTestCase.java
testsuite/src/test/java/org/jboss/galleon/cli/CliWrapper.java

https://issues.jboss.org/browse/GAL-144
UTF-8 instead of default platform encoding

[GAL-144] UTF-8 instead of default platform encoding

---

cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/PmSessionCommand.java
cli/src/main/java/org/jboss/galleon/cli/UniverseManager.java
cli/src/main/java/org/jboss/galleon/cli/cmd/FPLocationCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledProducerCompleter.java
cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/AddUniverseCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/installation/RemoveUniverseCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/CheckUpdatesCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/FindCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/GetInfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/ListFeaturePacksCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/UninstallCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenResolveFeaturePack.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractPluginsCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/DiffCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/AbstractFPProvisioningCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateGetInfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateRemoveUniverseCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/configuration/AbstractDefaultConfigCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/configuration/AbstractProvisionedDefaultConfigCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/fp/StateRemoveFeaturePackCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractProvisionedPackageCommand.java
cli/src/main/java/org/jboss/galleon/cli/tracking/BuildLayoutTracker.java
cli/src/main/java/org/jboss/galleon/cli/tracking/UpdatesTracker.java
testsuite/src/test/java/org/jboss/galleon/cli/UniverseTestCase.java

- Convey installation path in places where context sensitive information (eg: local universe names) are retrieved.

Fix for GAL-151, CLI, --dir option not propagated when resolving FPL

---

cli/src/main/java/org/jboss/galleon/cli/tracking/CliProgressTracker.java

Move the cursor at the end of the line.
Tested on fedora 28, Windows 10 and Mac.

Fix for GAL-166, cursor movement breaks tracker on fedora

---

cli/src/main/java/org/jboss/galleon/cli/Util.java
cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenMvnSettings.java
cli/src/test/java/org/jboss/galleon/cli/config/mvn/MvnSettingsTestCase.java
cli/src/test/resources/settings_cli_test.xml
cli/src/test/resources/settings_cli_test_mirror.xml
cli/src/test/resources/settings_cli_test_mirror_all.xml
cli/src/test/resources/settings_cli_test_proxy.xml

- Support for * and !<repo id>
- warn if external:* is used (not supported),
- added unit tests.

Fix for GAL-164, pattern in mvn mirror

---

cli/src/main/java/org/jboss/galleon/cli/terminal/InteractivePmCommandInvocation.java
pom.xml

- Removed workaround for GAL-167
- Upgrade to aesh 1.9

Fix for GAL-168 and upgrade to aesh 1.9

---

cli/src/main/java/org/jboss/galleon/cli/cmd/HelpCommand.java
cli/src/test/java/org/jboss/galleon/cli/HelpSupportTestCase.java

- Handle invalid command
- Complex command description was not displayed due to a lack of trimming.

Fix for GAL-179, GAL-180, CLI help issues

---

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java

Layers in CLI at install time. get-info to retrieve layers information. find to search for layers.
Re-order descriptions.

Follow-up for Fix for GAL-195

---

cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java
cli/src/main/java/org/jboss/galleon/cli/model/state/State.java
testsuite/src/test/java/org/jboss/galleon/cli/LayersTestCase.java

- Installing layers take passive+ as default value
- close runtime if an exception occurs at state creation time.

passive+ and runtime.close on error

---

cli/src/main/java/org/jboss/galleon/cli/CliMain.java
cli/src/main/java/org/jboss/galleon/cli/PmSession.java
cli/src/main/java/org/jboss/galleon/cli/tracking/BuildLayoutTracker.java
cli/src/main/java/org/jboss/galleon/cli/tracking/CliProgressTracker.java
cli/src/main/java/org/jboss/galleon/cli/tracking/ConfigsTracker.java
cli/src/main/java/org/jboss/galleon/cli/tracking/FindTracker.java
cli/src/main/java/org/jboss/galleon/cli/tracking/JBossModulesTracker.java
cli/src/main/java/org/jboss/galleon/cli/tracking/PackagesTracker.java
cli/src/main/java/org/jboss/galleon/cli/tracking/ProgressTrackers.java
cli/src/main/java/org/jboss/galleon/cli/tracking/UpdatesTracker.java

Check that the connection to terminal supports ANSI when initializing tracker.

Fix for GAL-236, CLI, Progress, wrong output for non ansi terminal

---

cli/src/main/java/org/jboss/galleon/cli/cmd/state/AbstractFPProvisionedCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractPackageCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractProvisionedPackageCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/PackagesUtil.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/ProvisionedPackageCommandActivator.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/StateExcludePackageCommand.java
cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/StateIncludePackageCommand.java
cli/src/main/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioning.java
cli/src/main/java/org/jboss/galleon/cli/model/state/State.java
core/src/main/java/org/jboss/galleon/config/FeaturePackDepsConfigBuilder.java
testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java
testsuite/src/test/java/org/jboss/galleon/cli/StateTestCase.java

- include/exclude packages for transitive dep.
- remove included/excluded for transitive dep.
- Automatically add a transitive dep when first including/excluding a package
- Remove empty transitive (not configured and no version) when removing included/excluded.
- Added tests

Fix for GAL-259, CLI, Including, excluding packages and transitive dependency issues

---

core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1Channel.java
core/src/test/java/org/jboss/galleon/installation/fpversions/MissingFpVersionTestCase.java
core/src/test/java/org/jboss/galleon/installation/fpversions/MissingFpVersionsTestCase.java

Throw proper exception to not update galleon1 FP.

Fix for GAL-262, Installed galleon1 FP breaks update

---

cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java

https://issues.jboss.org/browse/GAL-276

[GAL-276] CLI: install producer#build displays null as the channel in the report

---

cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java
cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java
cli/src/main/java/org/jboss/galleon/cli/model/state/State.java
core/src/main/java/org/jboss/galleon/ProvisioningManager.java
core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java
core/src/main/java/org/jboss/galleon/xml/util/FormattingXmlStreamWriter.java

https://issues.jboss.org/browse/GAL-277
[GAL-277] Formatting XML writer should use platform dependent line separator
https://issues.jboss.org/browse/GAL-278
[GAL-278] Provisioning manager encoding setting is used nowhere

[GAL-277], [GAL-278]

---

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java
cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java
cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/LayersConfigBuilder.java
docs/guide/tool/state.adoc
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java
testsuite/src/test/java/org/jboss/galleon/cli/AdvancedLayersTestCase.java

Issue https://issues.jboss.org/browse/GAL-296
* Allow to prefix a layer from the layers list with "-" to exclude it. Such layers are optional layer referenced from other provisioned layers.
* Allow to prefix a layer from the layers list with "+" to un-exclude it. Such layers should have been previously excluded.
* Added test and doc.
Issue https://issues.jboss.org/browse/GAL-297
* Changed the maven plugin default value to be passive+ when provisioning layers.

Fix for GAL-296 and GAL-297

---

README.adoc

See #278. I assume it is only an issue with the documentation and build should be done with `./do.sh build`.

[GAL-278] Command for building is ./do.sh build, not ./do.sh package.

---

maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/CreateProducerMojo.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/CreateProducersMojo.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/CreateUniverseMojo.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/FeaturePackInstallMojo.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/PropertyNames.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionFileStateMojo.java
maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java

https://issues.redhat.com/browse/GAL-323
Note I've added the `@Since 4.2.6` however if this doesn't make that release or we feel it should be in a 4.3 release let me know and I'll update it.
I feel this parameter is useful though. For example in WildFly we can skip provisioning servers for the test suite if the `-DskipTests` parameter is used.

[GAL-323] Add a skip configuration parameter to each MOJO.

---

cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java
core/src/main/java/org/jboss/galleon/universe/Channel.java

Issue: https://issues.redhat.com/browse/GAL-326
Maven is returning an empty string, we must filter it out. Fixed CLI display of null channel.

Fix for GAL-326, GAV based FP breaks update

---

pom.xml
release_process.adoc

Issue: https://issues.redhat.com/browse/GAL-331
* Removed invalid dependency scope.
* Updated release process doc to ensure CLI can provision wildfly.

Fix for GAL-331, CLI fails to provision WildFly

---

core/src/main/java/org/jboss/galleon/ProvisioningManager.java
core/src/main/java/org/jboss/galleon/util/IoUtils.java

Issue: https://issues.redhat.com/browse/GAL-335
Galleon could ignore exception when copying file that already exists (ie. was not deleted).

[GAL-335] Readonly files in server directory break update operation

---

core/pom.xml
core/src/main/java/org/jboss/galleon/Constants.java
core/src/main/java/org/jboss/galleon/ProvisioningManager.java
core/src/main/java/org/jboss/galleon/ProvisioningOption.java
core/src/main/java/org/jboss/galleon/diff/FsDiff.java
core/src/test/java/org/jboss/galleon/test/FeaturePackRepoTestBase.java
docs/guide/tool/state.adoc
pom.xml
testsuite/pom.xml
testsuite/src/test/java/org/jboss/galleon/cli/ChangesTestCase.java
testsuite/src/test/java/org/jboss/galleon/userchanges/test/UserChangesAfterInstallTestCase.java
testsuite/src/test/java/org/jboss/galleon/userchanges/test/UserChangesAfterUndoTestCase.java
testsuite/src/test/java/org/jboss/galleon/userchanges/test/UserChangesAfterUninstallTestCase.java
testsuite/src/test/java/org/jboss/galleon/userchanges/test/UserChangesTestBase.java
testsuite/src/test/java/org/jboss/galleon/userchanges/test/diff/UserChangesFullDiffTestCaseTestCase.java
testsuite/src/test/java/org/jboss/galleon/userchanges/test/diff/UserChangesOnlyConflictsDiffTestCase.java

Proposal for https://issues.redhat.com/browse/GAL-337
False-conflicts don't generate .glnew files
Added 'print-only-conflicts' option to allow displaying only real conflicts

[GAL-337] Handle 'false-conflicts' in upgrade diff

---

core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java
testsuite/src/test/java/org/jboss/galleon/userchanges/systemfiles/test/UserChangesAfterUpdatePlanWithDependencyTestCase.java

Issue: https://issues.redhat.com/browse/GAL-339

[GAL-339] system-paths are not used when feature pack uses dependencies

---

core/src/main/java/org/jboss/galleon/Constants.java
core/src/main/java/org/jboss/galleon/ProvisioningOption.java
core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java
core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java
docs/guide/provisioning-options/index.adoc

Issue: https://issues.redhat.com/browse/GAL-341

Fix for GAL-341, Allow to persist the provisioning config provided as input

---

core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java

Issue: https://issues.redhat.com/browse/GAL-345

[GAL-345] Record system paths only if provisioning is set up to record state

---

core/src/main/java/org/jboss/galleon/Constants.java
core/src/main/java/org/jboss/galleon/ProvisioningManager.java
core/src/main/java/org/jboss/galleon/xml/util/FormattingXmlStreamWriter.java

Issue: https://issues.redhat.com/browse/GAL-352
Upstream: #331

[GAL-352] Add system property to control line endings

---

common-api/src/main/java/org/jboss/galleon/Constants.java
core/src/main/java/org/jboss/galleon/ProvisioningOption.java
core/src/main/java/org/jboss/galleon/creator/FeaturePackBuilder.java
core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java
core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntime.java
core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java
core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java
core/src/main/java/org/jboss/galleon/spec/FeaturePackSpec.java
core/src/main/java/org/jboss/galleon/xml/FeaturePackXmlParser30.java
core/src/main/java/org/jboss/galleon/xml/FeaturePackXmlWriter.java
core/src/test/java/org/jboss/galleon/config/feature/stability/AbstractFeatureStabilityTestCase.java
core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureDefaultConfigStabilityCommunityPackageTestCase.java
core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureDefaultStabilityExcludePackageTestCase.java
core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureDefaultStabilityTestCase.java
core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureInvalidConfigStabilityTestCase.java
core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureInvalidPackageStabilityTestCase.java
core/src/test/java/org/jboss/galleon/featurepack/stability/AbstractFpStatibilityTestCase.java
core/src/test/java/org/jboss/galleon/featurepack/stability/FeaturePackSetCommunityStabilityTestCase.java

Issue: https://issues.redhat.com/browse/GAL-358

Fix for GAL-358, Introduce package and config stability

---

core/src/main/java/org/jboss/galleon/diff/FsDiff.java
core/src/main/java/org/jboss/galleon/diff/FsEntryFactory.java
core/src/test/java/org/jboss/galleon/diff/fs/test/FsDiffTestBase.java
core/src/test/java/org/jboss/galleon/diff/fs/test/NonReadableFolderFsTestCase.java

Issue: https://issues.redhat.com/browse/JBEAP-27451
Upstream PR: https://github.com/wildfly/galleon/pull/350
Upstream Issue: https://issues.redhat.com/browse/GAL-365

[GAL-365] Allow for non-readable files inside Galleon installation

---

core/src/main/java/org/jboss/galleon/Errors.java
core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java
core/src/main/java/org/jboss/galleon/spec/PackageDependencySpec.java
core/src/main/java/org/jboss/galleon/xml/PackageDepsSpecXmlParser.java
core/src/main/java/org/jboss/galleon/xml/PackageXmlWriter.java
core/src/main/resources/schema/galleon-layer-2_0.xsd
core/src/test/java/org/jboss/galleon/xml/test/LayerXmlParserTestCase.java
core/src/test/resources/xml/layer/layer-spec-test.xml
testsuite/src/test/java/org/jboss/galleon/pkg/stability/test/BasicPassivePlusDepIncludedTestCase.java
testsuite/src/test/java/org/jboss/galleon/pkg/stability/test/FailingNonExistingPackageInFeatureTestCase.java
testsuite/src/test/java/org/jboss/galleon/pkg/stability/test/SimpleNonExistingPackageInConfigTestCase.java
testsuite/src/test/java/org/jboss/galleon/pkg/stability/test/SimpleNonExistingPackageInDependencyTestCase.java
testsuite/src/test/java/org/jboss/galleon/pkg/stability/test/SimpleNonExistingPackageInFeatureTestCase.java
testsuite/src/test/java/org/jboss/galleon/pkg/stability/test/SimpleNonExistingPackageInLayerTestCase.java
testsuite/src/test/java/org/jboss/galleon/pkg/stability/test/SimpleNonExistingPackageInPackageTestCase.java

Issue: https://issues.redhat.com/browse/GAL-367

Fix for GAL-367, Allow to depend on an optional package only for a given stability level

---

core/src/main/java/org/jboss/galleon/runtime/DefaultBranchedConfigArranger.java

Issue: https://issues.redhat.com/browse/GAL-369

Fix for GAL-369, Introduce a System property to disable capability checks
