wildfly/galleon

cli/src/main/java/org/jboss/galleon/cli/CliMain.java, cli/src/main/java/org/jboss/galleon/cli/GavCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/SearchCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateProvisionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/UndoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/feature/StateRemoveFeatureCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractPackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/PackagesUtil.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainer.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureGroupsBuilder.java, cli/src/main/java/org/jboss/galleon/cli/model/FeaturePackInfo.java, cli/src/main/java/org/jboss/galleon/cli/model/state/ConfigProvisioning.java, cli/src/main/java/org/jboss/galleon/cli/path/FeatureContainerPathConsumer.java
- search and info are now directly accessible and are not contained in state command.
- aligned to complex feature naming
- evolved search to search inside dependencies.
- various fixes.
=> Fixed a bunch of findings

cli/src/main/java/org/jboss/galleon/cli/cmd/state/SearchCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateExportCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/model/PackageInfo.java, core/src/main/java/org/jboss/galleon/xml/BaseXmlWriter.java
- search inside the content of packages
- export XML to console
- aesh-extensions upgrade to 1.3
- some findings
=> Search inside the content of packages, export XML to console

cli/src/main/java/org/jboss/galleon/cli/CliMain.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/SearchCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java
https://issues.jboss.org/browse/GAL-9
Some straightforward changes required for the demo.
=> clear command, info exposes custom content

docs/guide/maven-plugin/install-feature-pack.adoc, docs/guide/maven-plugin/provision.adoc, docs/guide/provisioned-config/configs/arranging-features.adoc, docs/guide/provisioned-config/configs/config-element.adoc, docs/guide/provisioned-config/configs/index.adoc
https://issues.jboss.org/browse/GAL-18
=> [GAL-18] Complete the docs for 1.0.0.Final

core/src/main/java/org/jboss/galleon/universe/UniverseFactory.java, core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1UniverseFactory.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/NullParamForRequiredDynamicCapabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/OptionallyProvidedCapabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/SimpleUnsatisfiedDynamicCapabilityRequirementTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/UnknownParameterInCapabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/collection/EmptyCollectionForRequiredCapConsumerTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/collection/EmptyCollectionForRequiredCapProviderTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/collection/MissingCapProviderFromMultipleCollectionParamValuesTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/collection/MissingCapProviderTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/collection/ParamMissingCollectionTypeTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/statics/SimplestUnsatisfiedStaticCapabilityRequirementTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/ExcludedFeatureDependencyIncludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/ExcludedFeatureSpecDependencyIncludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/UnsatisfiedFeatureDependencyTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/UnsatisfiedFeatureSpecDependencyTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/param/reset/ResetOptionalCapabilityNillableParameterTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/param/unset/UnsetOptionalCapabilityNillableParameterTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/param/unset/UnsetRequiredCapabilityNillableParameterTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/collection/simpleid/SimpleMappedNonNillableRefToNoneTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/collection/simpleid/SimpleMappedRefInvalidTargetTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/collection/simpleid/SimpleNotMappedNonNillableRefToNoneTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/collection/simpleid/SimpleNotMappedRefInvalidTargetTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/ExcludedReferenceIncludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/NillableReferenceToAMissingFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/NillableReferenceToExcludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/NonNillableReferenceToAMissingFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/ReferenceIncludeExcludedTestCase.java, core/src/test/java/org/jboss/galleon/state/xml/test/ProvisionedStateXmlWriterTestCase.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenUniverseFactory.java
https://issues.jboss.org/browse/GAL-29
=> [GAL-29] remove universe.factory. prefix from universe factory id

maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenArtifact.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenUniverse.java, testsuite/src/test/java/org/jboss/galleon/universe/location/test/FeaturePackLocationResolverTestCase.java, testsuite/src/test/java/org/jboss/galleon/universe/maven/test/MavenUniverseLocationTestCase.java
https://issues.jboss.org/browse/GAL-30
=> [GAL-30] Allow version range for maven universe location

maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenArtifact.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenUniverse.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenUniverseFactory.java, maven-universe/src/test/java/org/jboss/galleon/universe/maven/test/MavenArtifactStringTestCase.java, testsuite/src/test/java/org/jboss/galleon/universe/maven/test/MavenUniverseLocationTestCase.java
https://issues.jboss.org/browse/GAL-31
=> [GAL-31] Support universe location shortened to groupId:artifactId

core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1FeaturePackCreator.java
Jira issue: https://issues.jboss.org/browse/GAL-52
=> [GAL-52] Create a temporal zip file before install a feature pack

maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/FeaturePackInstallMojo.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java
https://issues.jboss.org/browse/GAL-57
=> [GAL-57] remove resetting wildfly-specific properties from maven plugin

core/src/main/java/org/jboss/galleon/creator/UniverseFeaturePackCreator.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/AbstractMavenArtifactRepositoryManager.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/MavenArtifactRepositoryManager.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/repo/MavenArtifactVersion.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/repo/SimplisticMavenRepoManager.java, maven-universe/src/test/java/org/jboss/galleon/universe/maven/test/MavenArtifactLatestVersionTestCase.java, maven-universe/src/test/java/org/jboss/galleon/universe/maven/test/MavenArtifactVersionTestCase.java
https://issues.jboss.org/browse/GAL-58
=> [GAL-58] Allow releases to appear on /snapshot

core/src/main/java/org/jboss/galleon/layout/ProvisioningLayoutFactory.java, core/src/main/java/org/jboss/galleon/universe/UniverseResolver.java, core/src/main/java/org/jboss/galleon/universe/UniverseResolverBuilder.java, testsuite/src/test/java/org/jboss/galleon/universe/location/test/FeaturePackLocationResolverTestCase.java
Jira issue: https://issues.jboss.org/browse/GAL-45
=> [GAL-45] Allow adding feature pack local paths to universe resolvers

cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractPluginsCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/AbstractFPProvisioningCommand.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/state/State.java
fixed version issues observed with state info and adding feature-pack
=> Fix for GAL-59, CLI some version resolution issues

core/src/main/java/org/jboss/galleon/layout/ProvisioningLayoutFactory.java, testsuite/src/test/java/org/jboss/galleon/layout/test/NewConfigLayoutForZIPTestCase.java, testsuite/src/test/java/org/jboss/galleon/layout/test/ProvisioningLayoutTestBase.java
https://issues.jboss.org/browse/GAL-63
=> [GAL-63] Add ProvisioningLayoutFactory.newConfigLayout(featurePackZip)

core/src/main/java/org/jboss/galleon/Errors.java, core/src/main/java/org/jboss/galleon/universe/LatestVersionNotAvailableException.java, core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1Producer.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProducerDescription.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenChannel.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenErrors.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenLatestVersionNotAvailableException.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducer.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducerBase.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducerInstaller.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/repo/SimplisticMavenRepoManager.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenParsedProducerCallbackHandler.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenProducerXmlParser10.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenProducerXmlWriter.java, testsuite/src/test/java/org/jboss/galleon/universe/MvnUniverse.java, testsuite/src/test/java/org/jboss/galleon/universe/frequency/test/BetaAsDefaultFrequencyTestCase.java, testsuite/src/test/java/org/jboss/galleon/universe/frequency/test/BetaAsDefaultFrequencyWithAlphaReleasesTestCase.java
https://issues.jboss.org/browse/GAL-70
=> [GAL-70] Make the default frequency configurable

core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/config/FeaturePackDepsConfigBuilder.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, core/src/main/java/org/jboss/galleon/progresstracking/ProvisioningProgressCallback.java, core/src/main/java/org/jboss/galleon/progresstracking/ProvisioningProgressTracker.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java, core/src/test/java/org/jboss/galleon/plugin/test/MultiplePluginsTestCase.java
https://issues.jboss.org/browse/GAL-73
=> [GAL-73] Cache loaded plugins in ProvisioningLayout

cli/src/main/java/org/jboss/galleon/cli/CliMain.java, cli/src/main/java/org/jboss/galleon/cli/UniverseManager.java, cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractDynamicCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/InfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractPluginsCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/StateProvisionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/feature/StateAddFeatureCommand.java, cli/src/main/java/org/jboss/galleon/cli/path/FeatureContainerPathConsumer.java, cli/src/main/java/org/jboss/galleon/cli/resolver/PluginResolver.java
- feature-pack info to display plugin options.
- Disabled plugin options completion.
=> Fix for GAL-74, disable plugin options completion

cli/src/main/java/org/jboss/galleon/cli/AbstractStateCommand.java, cli/src/main/java/org/jboss/galleon/cli/PmSession.java, cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/ExploreCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/configuration/ConfigurationUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/PackagesUtil.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/state/State.java
https://issues.jboss.org/browse/GAL-87
=> [GAL-87] state new command fails with an NPE

pom.xml
https://issues.jboss.org/browse/GAL-95
=> [GAL-95] upgrade jboss-parent to 28

cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledFPLCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledProducerCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateUpdateCommand.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/InstallUpdateTestCase.java, testsuite/src/test/java/org/jboss/galleon/cli/PatchTestCase.java, testsuite/src/test/java/org/jboss/galleon/cli/PatchTransitiveDepTestCase.java
Fix for GAL-99, renamed state upgrade to state update
Fix for GAL-102, uninstall completer exposes direct and patches.
Fix for GAL-100, ProvisioningLayout.hasPatches
Fix for GAL-101, dedicated patches information
=> Some more CLI work.

cli/src/main/java/org/jboss/galleon/cli/AbstractStateCommand.java, cli/src/main/java/org/jboss/galleon/cli/PmSession.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateEditCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateExploreCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateUndoCommand.java, cli/src/main/java/org/jboss/galleon/cli/model/state/State.java, cli/src/main/java/org/jboss/galleon/cli/path/FeatureContainerPathConsumer.java, testsuite/src/test/java/org/jboss/galleon/cli/StateTestCase.java
- Added tests for uncovered state sub commands and some commands only available in editing mode.
- Revealed a bunch of findings.
=> Fix for GAL-105, state editing/exploration tests + fix findings

core/src/main/java/org/jboss/galleon/layout/ProvisioningLayoutFactory.java
https://issues.jboss.org/browse/GAL-109
=> [GAL-109] Expose home directory of ProvisioningLayoutFactory

cli/src/main/java/org/jboss/galleon/cli/tracking/JBossModulesTracker.java, cli/src/main/java/org/jboss/galleon/cli/tracking/ProgressTrackers.java, core/src/main/java/org/jboss/galleon/progresstracking/RecapOnPulseProgressCallback.java
https://issues.jboss.org/browse/GAL-111
=> [GAL-111] Add installation progress tracker for JBoss Modules

core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java
https://issues.jboss.org/browse/GAL-119
=> [WFGP-119] Add method ProvisioningLayout ProvisioningRuntime.getLayout()

cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfig.java, cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfigXml.java, testsuite/src/test/java/org/jboss/galleon/cli/CliWrapper.java
- Fix findings when running tests on Windows.
=> Follow up of GAL-121, fix to have tests to run on Windows

cli/src/main/java/org/jboss/galleon/cli/model/Caches.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureSpecsBuilder.java
Replace unzip filesystem navigation by direct access to Layout.
=> Fix for GAL-133, CLI Remove resolution/unzip when resolving feature specs

.travis.yml
https://issues.jboss.org/browse/GAL-135
Java 11 on travis-ci
=> [GAL-135] Java 11 on travis-ci

core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java
https://issues.jboss.org/browse/GAL-140
double if check removal
=> [GAL-140] double if check removal

cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenMvnSettings.java
https://issues.jboss.org/browse/GAL-143
regular expression fix
=> [GAL-143] regular expression fix

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/ToolModes.java, cli/src/main/java/org/jboss/galleon/cli/UniverseManager.java, cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/CheckUpdatesCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/FindCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/ListFeaturePacksCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, core/src/main/java/org/jboss/galleon/universe/Channel.java, core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1Channel.java, docs/guide/tool/state.adoc, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/AbstractMavenArtifactRepositoryManager.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenChannel.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/repo/MavenRepoManager.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/repo/SimplisticMavenRepoManager.java, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/FindFeaturePacksTestCase.java, testsuite/src/test/java/org/jboss/galleon/cli/ListFeaturePacksTestCase.java, testsuite/src/test/java/org/jboss/galleon/cli/UniverseTestCase.java
- find command.
- list-feature-packs revisited.
- Introduce Universe visitor.
- Commands unit tests.
- docs
=> Fix for GAL-149, list and find feature packs commands

docs/guide/generic-config-model/layers/overview.adoc, docs/guide/provisioned-config/config-element.adoc, docs/guide/provisioned-config/merges/model-only-configs.adoc, docs/guide/provisioned-config/merges/named-configs.adoc, docs/guide/provisioned-config/merges/named-model-configs.adoc
https://issues.jboss.org/browse/GAL-158
=> [GAL-158] Update config model related docs

pom.xml
https://issues.jboss.org/browse/GAL-159
=> [GAL-159] Upgrade to jboss-parent 29

core/src/main/java/org/jboss/galleon/runtime/ConfigModelStack.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/runtime/ResolvedConfig.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ConfigLayersSameFeaturePackTestCase.java
https://issues.jboss.org/browse/GAL-162
=> [GAL-162] Layers should not be arranged when resolved

cli/pom.xml, cli/src/main/java/org/jboss/galleon/cli/CliLogging.java, cli/src/main/java/org/jboss/galleon/cli/CliMain.java, cli/src/main/java/org/jboss/galleon/cli/PmSession.java, cli/src/main/java/org/jboss/galleon/cli/PmSessionCommand.java, cli/src/main/java/org/jboss/galleon/cli/UniverseManager.java, cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractDynamicCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractPathCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java, cli/src/main/java/org/jboss/galleon/cli/cmd/FPLocationCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledProducerCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/AbstractFPProvisionedDependentCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/configuration/AbstractProvisionedDefaultConfigCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractProvisionedPackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/resolver/ResourceResolver.java, cli/src/main/java/org/jboss/galleon/cli/terminal/CliShell.java, cli/src/main/java/org/jboss/galleon/cli/terminal/InteractiveInvocationProvider.java, cli/src/main/java/org/jboss/galleon/cli/terminal/InteractivePmCommandInvocation.java, content/bin/galleon-cli-logging.properties, content/bin/galleon.bat, content/bin/galleon.sh, do.sh, pom.xml
3 commits:
- aesh 1.8
- Usage of JBoss logging
- paging, scrolling,searching
=> Upgrade to aesh 1.8 and dependent issues

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/PmSessionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenGetInfo.java, cli/src/main/java/org/jboss/galleon/cli/cmd/mvn/MavenSetOffline.java, cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenCliSettings.java, cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfig.java, cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfigXml.java, cli/src/main/java/org/jboss/galleon/cli/terminal/InteractivePmCommandInvocation.java, cli/src/test/java/org/jboss/galleon/cli/config/mvn/MvnOfflineTestCase.java, docs/guide/tool/maven.adoc, testsuite/src/test/java/org/jboss/galleon/cli/MavenConfigTestCase.java
=> Fix for GAL-154, offline maven command

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/UniverseManager.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/FindCommand.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/InstallUpdateTestCase.java
- New option for the find command.
- docs and unit tests.
=> Fix for GAL-169, CLI, list maven universe resolved fp

maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/FeaturePackInstaller.java
https://issues.jboss.org/browse/GAL-175
=> [GAL-175] Maven plugin mojos are not closing ProvisioningManager

content/bin/galleon.bat, content/bin/galleon.sh, do.sh
Updated scripts to allow provisioning on JDK11.
=> Fix for GAL-181, JDK 11 require java.se module

cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java
- Display FPL when install is done.
- Clean-up get-info commands formatting.
=> Fix for GAL-184. CLI display installed FP

cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/CheckUpdatesCommand.java
- Make patch column optional.
- Removed universe ID from update channel if not required.
=> Fix for GAL-185. Update table should only mention patches if some patches are available

core/src/main/java/org/jboss/galleon/runtime/ConfigModelStack.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/LayerDependenciesWithDisabledInheritanceTestCase.java
https://issues.jboss.org/browse/GAL-188
=> [GAL-188] layers inherit=false should not affect layer dependencies

core/src/main/java/org/jboss/galleon/Errors.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/NullParamForRequiredDynamicCapabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/OptionallyProvidedCapabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/SimpleUnsatisfiedDynamicCapabilityRequirementTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/dynamic/UnknownParameterInCapabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/capability/statics/SimplestUnsatisfiedStaticCapabilityRequirementTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/ExcludedFeatureDependencyIncludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/ExcludedFeatureSpecDependencyIncludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/UnsatisfiedFeatureDependencyTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/deps/UnsatisfiedFeatureSpecDependencyTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/ExcludedReferenceIncludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/NillableReferenceToAMissingFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/NillableReferenceToExcludedFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/NonNillableReferenceToAMissingFeatureTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/OverwriteInitializedChildIdParamWhileNestingTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/refs/one2one/ReferenceIncludeExcludedTestCase.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ExcludeOptionalPackageFromConfigLayerTestCase.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ExcludeRequiredPackageFromConfigLayerTestCase.java
https://issues.jboss.org/browse/GAL-194
=> [GAL-194] Tests for exclusion of layer package dependencies

core/src/main/java/org/jboss/galleon/Constants.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/util/PathsUtils.java, core/src/main/java/org/jboss/galleon/util/StateHistoryUtils.java, testsuite/src/test/java/org/jboss/galleon/userchanges/test/UndoUpdateMatchingUserModifiedFileTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/test/UndoUpdateWithMatchingUserRemovedFileTestCase.java
https://issues.jboss.org/browse/GAL-173
=> [GAL-173] User changes not re-applied after undo

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/PmSession.java, cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledProducerCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Table.java, cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/FindCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/LayersConfigBuilder.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, cli/src/main/java/org/jboss/galleon/cli/model/ConfigInfo.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/state/State.java, cli/src/main/java/org/jboss/galleon/cli/tracking/FindTracker.java, cli/src/main/java/org/jboss/galleon/cli/tracking/ProgressTrackers.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/layout/FeaturePackLayout.java, core/src/main/java/org/jboss/galleon/xml/ConfigLayerSpecXmlParser.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/LayersTestCase.java
Layers in CLI at install time. get-info to retrieve layers information. find to search for layers.
=> Fix for GAL-195, Layers:CLI install, info and find

core/src/main/java/org/jboss/galleon/Errors.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, core/src/main/java/org/jboss/galleon/runtime/DefaultBranchedConfigArranger.java
https://issues.jboss.org/browse/GAL-141
=> [GAL-141] Eliminate e(x).printStackTrace() in the codebase

cli/src/main/java/org/jboss/galleon/cli/cmd/Table.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/Configuration.java, testsuite/src/test/java/org/jboss/galleon/cli/LayersTestCase.java
- Make passive the default when layers are installed
- Disabled layers completion.
- Display layers column if configuration contains layers.
=> Fix for GAL-202, Make passive the default when layers are installed

cli/src/main/java/org/jboss/galleon/cli/tracking/JBossModulesTracker.java, cli/src/main/java/org/jboss/galleon/cli/tracking/PackagesTracker.java
https://issues.jboss.org/browse/GAL-203
=> [GAL-203] Shorten progress tracking messages by excluding duplicate info

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java, cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledFPLCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/InstalledProducerCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/CheckUpdatesCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/UpdateCommand.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/InstallUpdateTestCase.java
- FPL in --feature-packs option
- In addition made --include-all-dependencies and --feature-packs disjonctive
- Fixed some descriptions, updated doc.
- Added unit test.
=> Fix for GAL-182, Allow to specify certain version when updating the installation

cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractDynamicCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/ProvisionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/UninstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/UpdateCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/plugin/AbstractPluginsCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateProvisionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/feature/StateAddFeatureCommand.java, core/src/main/java/org/jboss/galleon/Constants.java, core/src/main/java/org/jboss/galleon/ProvisioningOption.java, core/src/main/java/org/jboss/galleon/plugin/PluginOption.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java, core/src/main/java/org/jboss/galleon/util/CollectionUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/PluginOptionsTestCase.java, testsuite/src/test/java/org/jboss/galleon/plugin/options/test/BasicInstallWithPersistentPluginOptionsTestCase.java, testsuite/src/test/java/org/jboss/galleon/plugin/options/test/ExtraOptionsOverrideConfigOptionsTestCase.java, testsuite/src/test/java/org/jboss/galleon/plugin/options/test/InstalIntoConfiglWithPersistentPluginOptionsTestCase.java, testsuite/src/test/java/org/jboss/galleon/plugin/options/test/ProvisionOverConfigWithPersistentPluginOptionsTestCase.java
https://issues.jboss.org/browse/GAL-204
=> [GAL-204] Provisioning options should always be able to accept values

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, testsuite/src/test/java/org/jboss/galleon/cli/UniverseTestCase.java
=> Fix for GAL-210, Can't visualize universes added to an installation

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/cmd/CliErrors.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/LayersConfigBuilder.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/LayersTestCase.java
- install identified configs with --default-configs option
- Updated layers support
- Unit tests and doc.
=> Fix for GAL-209, Install only a subset of default configurations

cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/ToolModes.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/GetChangesCommand.java, core/src/main/java/org/jboss/galleon/diff/FsDiff.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/ChangesTestCase.java
- FsDiff.log rework.
- get-changes command.
- test and doc.
=> Fix for GAL-124, Command to display changes in an installation

core/src/main/java/org/jboss/galleon/diff/FsDiff.java, core/src/main/java/org/jboss/galleon/diff/FsEntry.java, core/src/main/java/org/jboss/galleon/diff/ProvisionedFeatureDiffCallback.java, core/src/main/java/org/jboss/galleon/diff/ProvisioningDiffProvider.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/xml/ProvisionedConfigXmlWriter.java, core/src/main/java/org/jboss/galleon/xml/ProvisionedStateXmlWriter.java, testsuite/src/test/java/org/jboss/galleon/patching/config/test/BasicConfigLayerTestCase.java, testsuite/src/test/java/org/jboss/galleon/patching/config/test/BasicConfigPatchingTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/AddedConfigTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/BasicConfigIncludeExcludeTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/BasicPersistFeatureIncludeExcludeAddTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/BasicStateDiffPlugin.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/ConfigIncludeExcludeInheritConfigsFalseIncludeConfigTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/ConfigIncludeExcludeInheritConfigsFalseIncludeModelTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/PersistChangesTestBase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/PersistFeatureIncludeExcludeAddWithInheritFeaturesFalseSpecIncludedTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/PersistFeatureIncludeExcludeAddWithInheritFeaturesFalseTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/PersistFeatureIncludeExcludeAddWithInheritFeaturesTrueSpecExcludedTestCase.java, testsuite/src/test/java/org/jboss/galleon/userchanges/persist/test/TestConfigsPersistingPlugin.java
https://issues.jboss.org/browse/GAL-217
=> [GAL-217] Cover PM.persistChanges() with tests

core/src/main/java/org/jboss/galleon/Constants.java, core/src/main/java/org/jboss/galleon/ProvisioningOption.java, core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntime.java, core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/runtime/PackageRuntime.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, testsuite/src/test/java/org/jboss/galleon/pkg/passiveplus/test/BasicPassivePlusDepIncludedTestCase.java, testsuite/src/test/java/org/jboss/galleon/pkg/passiveplus/test/ExplicitlyIncludedPassiveDepTestCase.java
https://issues.jboss.org/browse/GAL-215
=> [GAL-215] optional and passive policy (passive+)

core/src/main/java/org/jboss/galleon/Constants.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/diff/FsEntryFactory.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, testsuite/src/test/java/org/jboss/galleon/cli/ChangesTestCase.java, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java
https://issues.jboss.org/browse/GAL-220
=> [GAL-220] Introduce galleon.diff.filter file to feature packs

docs/guide/generic-config-model/features/caps.adoc, docs/guide/index.adoc, docs/guide/packages/dependencies.adoc, docs/guide/packages/effective-package-set/original-package-set.adoc, docs/guide/packages/metadata.adoc, docs/guide/patches/index.adoc, docs/guide/provisioning-options/index.adoc
https://issues.jboss.org/browse/GAL-222
=> [GAL-222] update the docs

pom.xml
https://issues.jboss.org/browse/GAL-223
=> [GAL-223] upgrade to jboss-parent 30

cli/src/main/java/org/jboss/galleon/cli/CliMain.java, cli/src/main/java/org/jboss/galleon/cli/HelpDescriptions.java, cli/src/main/java/org/jboss/galleon/cli/HelpSupport.java, cli/src/main/java/org/jboss/galleon/cli/cmd/HelpCommand.java, cli/src/main/resources/help/help-command.txt
Issue: https://issues.jboss.org/browse/GAL-161
=> [GAL-161] CLI - introduce multi-level dump for all the available commands

core/src/main/java/org/jboss/galleon/runtime/ConfigModelStack.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/UnsetParamConfigLayerTestCase.java
https://issues.jboss.org/browse/GAL-232
=> Fix for GAL-232, Parameters not unset from layers

testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ResetParamConfigLayerTestCase.java
https://issues.jboss.org/browse/GAL-232
=> [GAL-232] adding more tests for the issue

core/src/main/java/org/jboss/galleon/Errors.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, ide-configs/eclipse/templates.xml, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ProvisioningAnEmptyLayerTestCase.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ProvisioningMissingLayerTestCase.java
https://issues.jboss.org/browse/GAL-233
=> [GAL-233] Provisioning does not fail for layers that don't exist

core/src/main/java/org/jboss/galleon/Errors.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java
https://issues.jboss.org/browse/GAL-241
=> [GAL-241] option to log provisioning time at the end

cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/config/ConfigCustomizations.java, core/src/main/java/org/jboss/galleon/config/FeaturePackConfig.java, core/src/main/java/org/jboss/galleon/config/FeaturePackDepsConfig.java, core/src/main/java/org/jboss/galleon/config/PackageConfig.java, core/src/main/java/org/jboss/galleon/config/ProvisioningConfig.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/util/PathsUtils.java, core/src/test/java/org/jboss/galleon/test/FeaturePackRepoTestBase.java, core/src/test/java/org/jboss/galleon/test/PmTestBase.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/FeaturePackInstallMojo.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/FeaturePackInstaller.java, testsuite/src/test/java/org/jboss/galleon/state/test/SkipStatePersistenceOnFreshInstallTestCase.java, testsuite/src/test/java/org/jboss/galleon/state/test/SkipStatePersistenceOnReinstallTestCase.java
https://issues.jboss.org/browse/GAL-240
=> [GAL-240] an option to not record provisioning state in .galleon dir

maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/MvnMessageWriter.java
https://issues.jboss.org/browse/GAL-249
=> [GAL-249] Maven Log based MessageWriter impl for plugins

cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/LayersConfigBuilder.java, testsuite/src/test/java/org/jboss/galleon/cli/LayersTestCase.java
- Apply install on top of existing ProvisioningConfig (if any).
- Added tests.
=> Fix CLI install for default configs and layers

cli/src/main/java/org/jboss/galleon/cli/PmSession.java, core/src/main/java/org/jboss/galleon/repo/RepositoryArtifactInstaller.java, core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1Channel.java, core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1FeaturePackInstaller.java, core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1RepositoryManager.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/AbstractMavenArtifactRepositoryManager.java, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/InstallUpdateTestCase.java
- RepositoryArtifactInstaller implemented by Maven and Galleon1.
- Added local zip file and loc based installation from CLI tests.
=> Fix for GAL-253, Allow to install galleon1 fp from CLI

cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/LayersConfigBuilder.java, cli/src/main/java/org/jboss/galleon/cli/model/state/ConfigProvisioning.java, cli/src/main/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioning.java, cli/src/main/java/org/jboss/galleon/cli/model/state/State.java, cli/src/test/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioningTestCase.java, core/src/main/java/org/jboss/galleon/config/ConfigModel.java, core/src/main/java/org/jboss/galleon/config/FeaturePackConfig.java, core/src/main/java/org/jboss/galleon/config/ProvisioningConfig.java
https://issues.jboss.org/browse/GAL-255
=> [GAL-255] Remove getBuilder() methods from various xxxConfig classes

maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducer.java
Fix for https://issues.jboss.org/browse/GAL-256
=> Fix for GAL-256, MavenProducer.refresh must be synchronized

docs/guide/feature-packs/feature-pack-archive.adoc, docs/guide/feature-packs/feature-pack-xml.adoc
https://issues.jboss.org/browse/GAL-257
=> [GAL-257] Update docs for 3.0.1.Final

cli/src/main/java/org/jboss/galleon/cli/PmSessionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainer.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/PackageGroupsBuilder.java, core/src/main/java/org/jboss/galleon/runtime/PackageRuntime.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/AdvancedLayersTestCase.java
- get-info --optional-packages to retrieve optional/passive packages.
- added doc and tests.
=> Fix for GAL-258, Ability to list optional packages

cli/src/main/java/org/jboss/galleon/cli/PmSessionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/AbstractFPProvisionedCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractPackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractProvisionedPackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/PackagesUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/ProvisionedPackageCommandActivator.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/StateExcludePackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/StateIncludePackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainer.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/PackageGroupsBuilder.java, cli/src/main/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioning.java, cli/src/main/java/org/jboss/galleon/cli/model/state/State.java, core/src/main/java/org/jboss/galleon/config/FeaturePackDepsConfigBuilder.java, core/src/main/java/org/jboss/galleon/runtime/PackageRuntime.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/AdvancedLayersTestCase.java, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/StateTestCase.java
Fixes cherry-picked from master branch.
=> List Optional packages and packages handling with transitives

cli/src/main/java/org/jboss/galleon/cli/PmSessionCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/Headers.java, cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/AbstractFPProvisionedCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/InfoTypeCompleter.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/StateInfoUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractPackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/AbstractProvisionedPackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/PackagesUtil.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/ProvisionedPackageCommandActivator.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/StateExcludePackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/state/pkg/StateIncludePackageCommand.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainer.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/PackageGroupsBuilder.java, cli/src/main/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioning.java, cli/src/main/java/org/jboss/galleon/cli/model/state/State.java, core/src/main/java/org/jboss/galleon/config/FeaturePackDepsConfigBuilder.java, core/src/main/java/org/jboss/galleon/runtime/PackageRuntime.java, docs/guide/tool/state.adoc, testsuite/src/test/java/org/jboss/galleon/cli/AdvancedLayersTestCase.java, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/StateTestCase.java
=> Optional packages and transitive handling

core/src/main/java/org/jboss/galleon/Errors.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, core/src/main/java/org/jboss/galleon/universe/FeaturePackLocation.java, core/src/main/java/org/jboss/galleon/universe/Producer.java, core/src/main/java/org/jboss/galleon/universe/UniverseResolver.java, core/src/main/java/org/jboss/galleon/universe/galleon1/LegacyGalleon1Producer.java, core/src/test/java/org/jboss/galleon/featurepack/install/test/InstallFpWhichIsExistingTransitiveDependencyTestCase.java, core/src/test/java/org/jboss/galleon/featurepack/location/test/FeaturePackLocationStringTestCase.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProducerDescription.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducer.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducerDescription.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenProducerInstaller.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/MvnNoLocUniverse.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenChannelSpecXmlParser.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenChannelSpecXmlParser10.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenParsedProducerCallbackHandler.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenProducerSpecXmlParser.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenProducerSpecXmlParser10.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenProducerXmlParser.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenProducerXmlParser10.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/xml/MavenProducerXmlWriter.java, testsuite/src/test/java/org/jboss/galleon/defchannel/test/BasicDefaultChannelTestCase.java, testsuite/src/test/java/org/jboss/galleon/defchannel/test/MissingTheDefaultChannelTestCase.java, testsuite/src/test/java/org/jboss/galleon/defchannel/test/SingleChannelAsDefaultTestCase.java, testsuite/src/test/java/org/jboss/galleon/defchannel/test/TransitiveDepWithDefaultChannelTestCase.java, testsuite/src/test/java/org/jboss/galleon/defchannel/test/TransitiveDepWithDefaultChannelVersionConflictTestCase.java, testsuite/src/test/java/org/jboss/galleon/universe/MvnUniverse.java, testsuite/src/test/java/org/jboss/galleon/universe/SingleUniverseTestBase.java
https://issues.jboss.org/browse/GAL-267
=> [GAL-267] Support for the default channel

cli/src/main/java/org/jboss/galleon/cli/HelpSupport.java, cli/src/main/java/org/jboss/galleon/cli/cmd/AbstractDynamicCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/featurepack/GetInfoCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/model/FeatureContainers.java, cli/src/main/java/org/jboss/galleon/cli/model/state/ConfigProvisioning.java, cli/src/main/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioning.java, cli/src/main/java/org/jboss/galleon/cli/model/state/Provisioning.java, core/src/main/java/org/jboss/galleon/runtime/FpStack.java, core/src/test/java/org/jboss/galleon/config/feature/param/type/parser/formatexpr/CollectionOfCompositeTypesTestCase.java
Make inner classes static to limit references to outer class
Use entrySet for maps to (micro-)improve performance
Issue: https://issues.jboss.org/browse/GAL-266
=> GAL-266 - Make inner classes static, use entrySet for maps

core/src/main/java/org/jboss/galleon/runtime/ConfigModelStack.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ConfigLayerIncludedInModelOnlyConfigTestCase.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ExcludeFeatureFromInheritedConfigLayerIncludedFromAGroupTestCase.java
https://issues.jboss.org/browse/GAL-268
=> [GAL-268] Layers included in model.xml don't appear in provisioned.xml

pom.xml
https://issues.jboss.org/browse/GAL-270
=> [3.x][GAL-270] Use https URLs in pom repository configuration

pom.xml
https://issues.jboss.org/browse/GAL-270
=> [GAL-270] Use https URLs in pom repository configuration

cli/src/main/java/org/jboss/galleon/cli/model/state/FeaturePackProvisioning.java, core/src/main/java/org/jboss/galleon/config/FeaturePackConfig.java, core/src/main/java/org/jboss/galleon/runtime/FpStack.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/xml/ProvisioningXmlWriter.java, core/src/main/resources/schema/galleon-provisioning-3_0.xsd, core/src/test/java/org/jboss/galleon/xml/test/IncludeDefaultTestCase.java, core/src/test/java/org/jboss/galleon/xml/test/ProvisioningXmlExcludesIncludesTestCase.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/FeaturePack.java, testsuite/src/test/java/org/jboss/galleon/transitive/test/IncludeExcludedPackagesInTransitiveDepTestCase.java
https://issues.jboss.org/browse/GAL-274
=> [GAL-274] Re-enabling disabled package inheritance for transitive deps

cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfig.java
https://issues.jboss.org/browse/GAL-272
=> [GAL-272] Use https URLs for default repositories

core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/CircularFpDepWithConfigLayerTestCase.java
https://issues.jboss.org/browse/GAL-271
=> [GAL-271] ProvisioningRuntimeBuilder.resolveConfigLayer should detect circular fp dep

maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionFileStateMojo.java
"provision-file" goal, relies on the presence of an XML file in project.
=> Fix for GAL-283, Maven goal to provision a server from a provisioning file

cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenCliSettings.java, cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenConfig.java, cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenMvnSettings.java, cli/src/main/java/org/jboss/galleon/cli/config/mvn/MavenProxySelector.java, cli/src/test/java/org/jboss/galleon/cli/config/mvn/MvnSettingsTestCase.java, cli/src/test/resources/settings_cli_test_proxy_no_repo.xml, cli/src/test/resources/settings_cli_test_with_default.xml
Fixed proxy handling
Added unit test
Manual testing using squid proxy server
=> Fix for GAL-285, Maven proxy support not proxying repositories

core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, testsuite/src/test/java/org/jboss/galleon/provision/config/layers/test/ExcludeFeatureFromDependantConfigLayerTestCase.java, testsuite/src/test/java/org/jboss/galleon/transitive/test/IncludeNonDefaultConfigWithDisabledConfigInheritanceTestCase.java
https://issues.jboss.org/browse/GAL-294
=> [GAL-294] Non-default configs are not included with the  element

core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, testsuite/src/test/java/org/jboss/galleon/maven/noloc/test/OverrideFplVersionOfTransitiveDepWithGavVariation2TestCase.java
https://issues.redhat.com/browse/GAL-303
=> [GAL-303] Overriding FPL of a transitive dep with Maven coords may fail

core/src/main/java/org/jboss/galleon/layout/FeaturePackLayout.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/spec/FeaturePackSpec.java, docs/guide/feature-pack-deps/disabling-inheritance.adoc, testsuite/src/test/java/org/jboss/galleon/layout/update/test/SimpleApplyUpdateForFpsInstalledUsingGavInPlaceOfFplTestCase.java, testsuite/src/test/java/org/jboss/galleon/maven/noloc/test/OverrideFplVersionOfTransitiveDepWithGavVariation3TestCase.java
[GAL-305] Can't suppress an overridden package from a depended-on f-p
https://issues.redhat.com/browse/GAL-304
https://issues.redhat.com/browse/GAL-305
=> [GAL-304] Can't provision a feature-pack with GAV dependencies

core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntime.java, testsuite/src/test/java/org/jboss/galleon/cli/CliTestUtils.java, testsuite/src/test/java/org/jboss/galleon/cli/StateTestCase.java
* Handle the null case.
* Added new test.
=> Fix for GAL-312, NPE when editing an installation

cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/InstallCommand.java, cli/src/main/java/org/jboss/galleon/cli/cmd/maingrp/LayersConfigBuilder.java, testsuite/src/test/java/org/jboss/galleon/cli/AdvancedLayersTestCase.java
Issues:
https://issues.redhat.com/browse/GAL-315
https://issues.redhat.com/browse/GAL-316
=> Fix for GAL-315 and GAL-316

.travis.yml, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/ProvisionStateMojo.java
https://issues.redhat.com/browse/GAL-321
=> [GAL-321] If the version of the feature-pack is missing from the config, look it up among the project deps

core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntime.java, core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/runtime/PackageRuntime.java, testsuite/src/test/java/org/jboss/galleon/pkg/passiveplus/test/FailingPassivePlusDepIncludedTestCase.java
https://issues.redhat.com/browse/GAL-325
Check whether passive optional dependencies are satisfied in cycles to make sure cascading inclusions work properly.
=> [GAL-325] Invalid package processing order with passive dependencies

core/src/main/resources/schema/galleon-provisioning-3_0.xsd, core/src/test/java/org/jboss/galleon/xml/test/ProvisioningWithConfigTestCase.java, core/src/test/resources/xml/provisioning/provisioning-config2.xml
* Added layers and config-deps to config
* Added origin and patches to feature-pack
=> Fix for GAL-328, Update provisioning 3.0 xsd to reflect actual support

maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/FpMavenErrors.java, maven-plugin/src/main/java/org/jboss/galleon/maven/plugin/util/AbstractMavenArtifactRepositoryManager.java, maven-universe/src/main/java/org/jboss/galleon/universe/maven/repo/MavenRepoManager.java
Issue: https://issues.redhat.com/browse/GAL-333
Exposing `RepositorySystem#resolveArtifacts` in `MavenRepoManager` interface. Example usage in wildfly-galleon-plugins: https://github.com/wildfly/galleon-plugins/compare/main...spyrkob:bulk_resolve_60
=> [GAL-333] Bulk artifact resolve operation

core/src/main/java/org/jboss/galleon/Constants.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/creator/FeaturePackBuilder.java, core/src/main/java/org/jboss/galleon/diff/FsDiff.java, core/src/main/java/org/jboss/galleon/layout/ProvisioningLayout.java, core/src/main/java/org/jboss/galleon/layout/SystemPaths.java, core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntime.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java, core/src/main/java/org/jboss/galleon/spec/FeaturePackSpec.java, core/src/main/java/org/jboss/galleon/xml/FeaturePackXmlParser30.java, core/src/main/java/org/jboss/galleon/xml/FeaturePackXmlWriter.java, core/src/main/java/org/jboss/galleon/xml/XmlParsers.java, core/src/main/resources/schema/galleon-feature-pack-3_0.xsd, core/src/test/java/org/jboss/galleon/featurepack/xml/test/FeaturePackXml30ParserTestCase.java, core/src/test/java/org/jboss/galleon/layout/SystemPathsTest.java, core/src/test/resources/xml/feature-pack/feature-pack-3.0-absolute-system-path.xml, docs/guide/feature-packs/feature-pack-xml.adoc, docs/guide/user-managed-content/index.adoc, testsuite/src/test/java/org/jboss/galleon/userchanges/systemfiles/test/UserChangesAfterUpdatePlanTestCase.java
Issue: https://issues.redhat.com/browse/GAL-336
related galleon-plugins PR: https://github.com/wildfly/galleon-plugins/pull/234
=> [GAL-336] Adding system-paths setting to feature-pack

cli/pom.xml, maven-plugin/pom.xml, maven-universe/pom.xml, pom.xml
Issue: https://issues.redhat.com/browse/GAL-342
=> Fix for GAL-342, Rework maven plugin dependencies

core/src/main/java/org/jboss/galleon/Constants.java, core/src/main/java/org/jboss/galleon/ProvisioningOption.java, core/src/main/java/org/jboss/galleon/layout/SystemPaths.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java, core/src/main/java/org/jboss/galleon/universe/UniverseResolver.java, docs/guide/provisioning-options/index.adoc
Issue: https://issues.redhat.com/browse/GAL-343
=> [GAL-343] Export system paths and make UniverseResolver extendable

cli/src/main/java/org/jboss/galleon/cli/tracking/ConfigsTracker.java, cli/src/main/java/org/jboss/galleon/cli/tracking/ExtraConfigsTracker.java, cli/src/main/java/org/jboss/galleon/cli/tracking/ProgressTrackers.java
Issue: https://issues.redhat.com/browse/GAL-346
=> Fix for GAL-346, Tracker for extra configuration generations and delayed generation

maven-universe/src/main/java/org/jboss/galleon/universe/maven/MavenArtifact.java
Issue: https://issues.redhat.com/browse/GAL-348
=> Fix for GAL-348, Attach metadata to MavenArtifact

core/src/main/java/org/jboss/galleon/layout/FeaturePackLayout.java, core/src/main/java/org/jboss/galleon/spec/ConfigLayerSpec.java, core/src/main/java/org/jboss/galleon/xml/ConfigLayerXmlParser20.java, core/src/main/java/org/jboss/galleon/xml/XmlParsers.java
Issues:
https://issues.redhat.com/browse/GAL-349
https://issues.redhat.com/browse/GAL-350
=> Fix for GAL-349, GAL-350, ability to add metadata into layers. API to read model.xml

core/src/main/java/org/jboss/galleon/Constants.java, core/src/main/java/org/jboss/galleon/ProvisioningManager.java, core/src/main/java/org/jboss/galleon/xml/util/FormattingXmlStreamWriter.java
Issue: https://issues.redhat.com/browse/GAL-352
=> [GAL-352] Line endings

core/src/main/java/org/jboss/galleon/ProvisioningManager.java
Issue: https://github.com/wildfly/galleon/pull/333
=> [GAL-353] Sort hashes entries in .galleon/hashes folder

pom.xml
https://issues.redhat.com/browse/GAL-356
=> [GAL-356] Upgrade the JBoss staxmapper to 1.5.0.Final.

api/src/main/java/org/jboss/galleon/api/GalleonBuilder.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntime.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/main/java/org/jboss/galleon/spec/FeaturePackSpec.java
Issues:
* https://issues.redhat.com/browse/GAL-359
* https://issues.redhat.com/browse/GAL-360
=> Fix for GAL-359 and GAL-360

api/src/main/java/org/jboss/galleon/api/ProvisioningImpl.java, core/src/main/java/org/jboss/galleon/runtime/FeaturePackRuntime.java, core/src/main/java/org/jboss/galleon/runtime/ProvisioningRuntimeBuilder.java, core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureCommunityStabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureDefaultConfigStabilityCommunityPackageTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/stability/FeatureExperimentalStabilityTestCase.java, core/src/test/java/org/jboss/galleon/config/feature/stability/FeaturePreviewStabilityTestCase.java, core/src/test/java/org/jboss/galleon/featurepack/stability/FeaturePackSetExperimentalStabilityTestCase.java
Issue: https://issues.redhat.com/browse/GAL-361
=> Fix for GAL-361, Feature pack config stability level improperly constrains provisioning

common-api/src/main/java/org/jboss/galleon/xml/util/FormattingXmlStreamWriter.java, core/src/main/java/org/jboss/galleon/xml/util/FormattingXmlStreamWriter.java
Also FormattingXmlStreamWriter.writeEmptyElement(...)
=> GAL-368 Fix FormattingXmlStreamWriter.writeStartElement(...) delegation

api/src/main/java/org/jboss/galleon/api/GalleonBuilder.java, api/src/main/java/org/jboss/galleon/api/ProvisioningImpl.java, api/src/test/java/org/jboss/galleon/api/GalleonBuilderTestCase.java
Issue: https://issues.redhat.com/browse/GAL-370
=> [GAL-370] Move unused classloader error to debug level

core/src/main/java/org/jboss/galleon/xml/ConfigXmlWriter.java, core/src/main/java/org/jboss/galleon/xml/ProvisionedConfigXmlWriter.java
Issue: https://issues.redhat.com/browse/GAL-371
=> [GAL-371] Keep properties and parameters in provisioned.xml ordered alphabetically

core/src/main/java/org/jboss/galleon/layout/FeaturePackDescriber.java, core/src/main/java/org/jboss/galleon/layout/FeaturePackLayout.java
Issues
https://issues.redhat.com/browse/GAL-372
https://issues.redhat.com/browse/GAL-373
=> GAL-372 and GAL-373
